#!/bin/bash

# gets staged git files to use with lint-staged in client/package.json
staged_files=$(git diff --cached --name-status --diff-filter=AM | grep -E '\.(py)$' | cut -f 2 | grep -E 'appserver' | sed 's/appserver\///g')
staged_renamed_files=$(git diff --cached --name-status --diff-filter=R | grep -E '\.(py)$' | cut -f 3 | grep -E 'appserver' | sed 's/appserver\///g')
all_staged_files="${staged_files}\n${staged_renamed_files}"

echo ${all_staged_files} | docker exec appserver mypy .
echo ${all_staged_files} | docker exec appserver pycodestyle .
