# Github Dependabot configuration file
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

# Sadly this file does not support YAML anchors, nor action definitions
# Therefore we have to repeat the same configuration for each action

version: 2
updates:
  # Appserver
  - package-ecosystem: "pip"
    directory: "/appserver"
    versioning-strategy: increase
    open-pull-requests-limit: 0  # Disable PRs which are not security updates
    schedule:
      interval: "weekly"
    reviewers:
      - esanche06
      - skitionek
  - package-ecosystem: "docker"
    directory: "/appserver"
    open-pull-requests-limit: 0  # Disable PRs which are not security updates
    schedule:
      interval: "weekly"
    reviewers:
      - esanche06
      - skitionek

  # ArangoDB
  - package-ecosystem: "docker"
    directory: "/arangodb"
    open-pull-requests-limit: 0  # Disable PRs which are not security updates
    schedule:
      interval: "weekly"
    reviewers:
      - esanche06
      - skitionek

  # Cache Invalidator
  - package-ecosystem: "pip"
    directory: "/cache-invalidator"
    versioning-strategy: increase
    open-pull-requests-limit: 0  # Disable PRs which are not security updates
    schedule:
      interval: "weekly"
    reviewers:
      - esanche06
      - skitionek
  - package-ecosystem: "docker"
    directory: "/cache-invalidator"
    open-pull-requests-limit: 0  # Disable PRs which are not security updates
    schedule:
      interval: "weekly"
    reviewers:
      - esanche06
      - skitionek

  # Client
  - package-ecosystem: "npm"
    directory: "/client"
    versioning-strategy: increase
    open-pull-requests-limit: 0  # Disable PRs which are not security updates
    schedule:
      interval: "weekly"
    reviewers:
      - esanche06
      - skitionek
  - package-ecosystem: "docker"
    directory: "/client"
    open-pull-requests-limit: 0  # Disable PRs which are not security updates
    schedule:
      interval: "weekly"
    reviewers:
      - esanche06
      - skitionek

  # Elasticsearch
  - package-ecosystem: "docker"
    directory: "/elasticsearch"
    open-pull-requests-limit: 0  # Disable PRs which are not security updates
    schedule:
      interval: "weekly"
    reviewers:
      - esanche06
      - skitionek

  # Filebeat
  - package-ecosystem: "docker"
    directory: "/filebeat"
    open-pull-requests-limit: 0  # Disable PRs which are not security updates
    schedule:
      interval: "weekly"
    reviewers:
      - esanche06
      - skitionek

  # Logstash
  - package-ecosystem: "docker"
    directory: "/logstash"
    open-pull-requests-limit: 0  # Disable PRs which are not security updates
    schedule:
      interval: "weekly"
    reviewers:
      - esanche06
      - skitionek

  # Metricbeat
  - package-ecosystem: "docker"
    directory: "/metricbeat"
    open-pull-requests-limit: 0  # Disable PRs which are not security updates
    schedule:
      interval: "weekly"
    reviewers:
      - esanche06
      - skitionek

  # Statistical Enrichment
  - package-ecosystem: "pip"
    directory: "/statistical-enrichment"
    versioning-strategy: increase
    open-pull-requests-limit: 0  # Disable PRs which are not security updates
    schedule:
      interval: "weekly"
    reviewers:
      - esanche06
      - skitionek
  - package-ecosystem: "docker"
    directory: "/statistical-enrichment"
    open-pull-requests-limit: 0  # Disable PRs which are not security updates
    schedule:
      interval: "weekly"
    reviewers:
      - esanche06
      - skitionek

