# Github Dependabot configuration file
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

x-tracking-options: &tracking-options
  versioning-strategy: increase
  open-pull-requests-limit: 0  # Disable PRs which are not security updates
  schedule:
    interval: "weekly"

version: 2
updates:
  # Appserver
  - package-ecosystem: "pipenv"
    directory: "/appserver"
    <<: *tracking-options
  - package-ecosystem: "docker"
    directory: "/appserver"
    <<: *tracking-options

  # ArangoDB
  - package-ecosystem: "docker"
    directory: "/arangodb"
    <<: *tracking-options

  # Cache Invalidator
  - package-ecosystem: "pipenv"
    directory: "/cache-invalidator"
    <<: *tracking-options
  - package-ecosystem: "docker"
    directory: "/cache-invalidator"
    <<: *tracking-options

  # Client
  - package-ecosystem: "yarn"
    directory: "/client"
    <<: *tracking-options
  - package-ecosystem: "docker"
    directory: "/client"
    <<: *tracking-options

  # Elasticsearch
  - package-ecosystem: "docker"
    directory: "/elasticsearch"
    <<: *tracking-options

  # Filebeat
  - package-ecosystem: "docker"
    directory: "/filebeat"
    <<: *tracking-options

  # Logstash
  - package-ecosystem: "docker"
    directory: "/logstash"
    <<: *tracking-options

  # Metricbeat
  - package-ecosystem: "docker"
    directory: "/metricbeat"
    <<: *tracking-options

  # Statistical Enrichment
  - package-ecosystem: "pipenv"
    directory: "/statistical-enrichment"
    <<: *tracking-options
  - package-ecosystem: "docker"
    directory: "/statistical-enrichment"
    <<: *tracking-options

