# About this file: https://www.gitpod.io/docs/config-gitpod-file)
image:
  file: .gitpod.Dockerfile

tasks:
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # Admin tasks
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - before: git submodule deinit --all -f

  - name: Google Cloud Platform
    init: make gcloud
    command: gp sync-done gcloud-setup
    openIn: left
    openMode: split-left

  - name: Fetch LMDB files
    init: |
      make fetch-lmdb
      gp sync-done fetch-lmdb

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # Backend tasks
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - name: Run Docker Compose backing services
    init: docker-compose pull
    command: |
      docker-compose up --watch --detach
      gp sync-done services-up
      docker-compose logs --follow

  - name: Run Appserver Flask app
    before: cd appserver
    init: |
      pipenv install --dev --keep-outdated
      gp sync-done appserver-init
    command: |
      gp sync-await services-up
      pipenv run flask run
    env:
      FLASK_APP: app
      FLASK_ENV: Development

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # Frontend tasks
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - name: Run Angular frontend app
    before: cd client
    init: |
      yarn install
      gp sync-done frontend-init
    command: yarn run dev-start

  - name: Statistical Enrichment
    before: cd statistical-enrichment
    init: pipenv install --dev --keep-outdated
    command: |
      gp ports await 7601 && \
      gp ports await 7687 && \
      pipenv run flask run --debugger
    env:
      FLASK_APP: statistical_enrichment
      FLASK_ENV: Development

  - name: Cache Invalidator
    before: cd cache-invalidator
    init: pipenv install --dev --keep-outdated
    command: pipenv run python main.py

  - name: Download LMDB data files
    before: |
      gp sync-await gcloud-setup
      gsutil cp gs://lmdb/public/lmdb_v6.tgz .
      tar zxfg lmdb.tgz

ports:
  - port: 4200
    name: client
    description: Angular Live Development Server
    visibility: public
    onOpen: open-preview

  - port: 5000
    name: appserver
    description: Flask development server
    visibility: public
    onOpen: notify

  - port: 7600
    name: pdfparser
    description: PDF Parser service
    onOpen: ignore

  - port: 5432
    name: postgres
    description: PostgresQL database
    onOpen: ignore

  - port: 9200
    name: elasticsearch
    description: Elasticsearch service
    onOpen: ignore

  - port: 7474
    name: Neo4j Browser
    description: Neo4j browser UI
    visibility: public
    onOpen: notify

  - port: 7687
    name: Neo4j Bolt
    description: Neo4j Bolt port
    onOpen: ignore

  - port: 5010
    name: Statistical Enrichment
    description: Statistical Enrichment Flask microservice
    visibility: public
    onOpen: notify

vscode:
  extensions:
    - ms-python.python
    - donjayamanne.python-extension-pack
    - almenon.arepl
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - mgesbert.python-path
    - christian-kohler.path-intellisense
    - DavidAnson.vscode-markdownlint
    - cyrilletuzi.angular-schematics
    - manuth.eslint-language-service
    - Angular.ng-template

gitConfig:
  diff.ignoreSubmodules: all
