# About this file: https://www.gitpod.io/docs/config-gitpod-file)
image:
  file: .gitpod.Dockerfile

tasks:
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # Admin tasks
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - name: Fetch LMDB files
    init: >
      git submodule deinit --all -f &&
      make lmdb-fetch

  - name: Google Cloud Platform
    command: >
      make gcloud-setup &&
      gp sync-done gcloud-setup

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # Backend tasks
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - name: Run Docker Compose backing services
    init: docker compose build --pull
    command: >
      docker compose up -d --wait &&
      gp sync-done services-up &&
      docker compose logs --follow

  - name: Run Appserver Flask app
    before: cd appserver
    init: >
      pipenv install --dev --keep-outdated &&
      gp sync-done appserver-init
    command: >
      gp sync-await services-up &&
      pipenv run flask run
    env:
      FLASK_APP: app
      FLASK_ENV: Development

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # Frontend tasks
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - name: Run Angular frontend app
    before: cd client
    init: yarn install
    command: >
      gp sync-done frontend-init &&
      yarn run dev-start

  - name: Statistical Enrichment
    before: cd statistical-enrichment
    init: pipenv install --dev --keep-outdated
    command: >
      gp ports await 7687 &&
      pipenv run flask run
    env:
      FLASK_APP: statistical_enrichment
      FLASK_ENV: Development

  - name: Cache Invalidator
    before: cd cache-invalidator
    init: pipenv install --dev --keep-outdated
    command: >
      gp ports await 7687 &&
      gp ports await 6379 &&
      pipenv run python main.py

ports:
  - port: 4200
    name: client
    description: Angular Live Development Server
    visibility: public
    onOpen: open-preview

  - port: 5000
    name: appserver
    description: Flask development server
    visibility: public
    onOpen: notify

  - port: 7600
    name: pdfparser
    description: PDF Parser service
    onOpen: ignore

  - port: 5432
    name: postgres
    description: PostgresQL database
    onOpen: ignore

  - port: 9200
    name: elasticsearch
    description: Elasticsearch service
    onOpen: ignore

  - port: 7474
    name: Neo4j Browser
    description: Neo4j browser UI
    visibility: public
    onOpen: notify

  - port: 7687
    name: Neo4j Bolt
    description: Neo4j Bolt port
    onOpen: ignore

  - port: 5010
    name: Statistical Enrichment
    description: Statistical Enrichment Flask microservice
    visibility: public
    onOpen: notify

vscode:
  extensions:
    - ms-python.python
    - almenon.arepl
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - mgesbert.python-path
    - christian-kohler.path-intellisense
    - cyrilletuzi.angular-schematics
    - manuth.eslint-language-service
    - Angular.ng-template
    - littlefoxteam.vscode-python-test-adapter

gitConfig:
  diff.ignoreSubmodules: all

github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: prevent-merge-on-error
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
