version: '3.8'

services:
    appserver:
        ports:
            - 5000:5000
        env_file:
            - ./.env
        volumes:
            # Service account file needs access to Google Cloud Storage (Bucket)
            - ${GCP_SERVICE_ACCOUNT:-/home/ansible/ansible_service_account.json}:/home/n4j/neo4japp/ansible_service_account.json
            - ${LMDB_DIR:-/home/ansible/lmdb}:/home/n4j/neo4japp/services/annotations/lmdb
        networks:
            - frontend
            - backend

    webserver:
        ports:
            - 80:80
            - 443:443
        networks:
            - frontend

    nlpapi:
        expose:
            - 5001
        env_file:
            - ./.env
        volumes:
            - ${NLP_DIR:-/home/ansible/models}:/models
        networks:
            - backend

    cache-invalidator:
        env_file:
            - ./.env
        networks:
            - backend

    redis:
        networks:
            - backend

networks:
    frontend:
    backend:
