version: "3.8"

# ----------------------------------------
# Backing services
# ----------------------------------------
services:
  postgres:
    image: postgres:14
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres

  neo4j:
    image: neo4j:4.4-community
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4JLABS_PLUGINS=["apoc", "n10s"]

  pdfparser:
    image: ghcr.io/sbrg/***ARANGO_DB_NAME***-pdfparser
    restart: unless-stopped
    tty: true
    ports:
      - 7600:7600

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379

  elasticsearch:
    image: ghcr.io/sbrg/***ARANGO_DB_NAME***-elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - http.max_content_length=200mb
    ports:
      - 9200:9200
