version: "3.8"

services:
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.10.1
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - elastic
    depends_on:
      - elasticsearch

  logstash:
    container_name: logstash
    build:
      dockerfile: Dockerfile
      context: logstash
    ports:
      - 9600:9600
    expose:
      - 5000
      - 5044
    networks:
      - elastic
    depends_on:
      - elasticsearch

  filebeat:
    container_name: filebeat
    user: ***ARANGO_USERNAME***
    build:
      context: filebeat/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # This is needed for filebeat to load container log path as specified in filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    environment:
      - ELASTICSEARCH_HOST="http://elasticsearch:9200"
      - KIBANA_HOST="http://kibana:5601"
      - ELASTICSEARCH_USERNAME="elastic"
      - ELASTICSEARCH_PASSWORD="changeme"
    command: ["--strict.perms=false"]
    depends_on:
      - elasticsearch
      - logstash
    networks:
      - elastic
