version: '3.8'

services:
    appserver:
        image: ${REGISTRY:-gcr.io/able-goods-221820}/kg-appserver-staging:${GITHUB_HASH:-latest}
        ports:
            - "5000:5000"
        env_file:
            - ./.env
        volumes:
            - /srv/lmdb/chemicals:/home/n4j/neo4japp/services/annotations/lmdb/chemicals
            - /srv/lmdb/compounds:/home/n4j/neo4japp/services/annotations/lmdb/compounds
            - /srv/lmdb/diseases:/home/n4j/neo4japp/services/annotations/lmdb/diseases
            - /srv/lmdb/genes:/home/n4j/neo4japp/services/annotations/lmdb/genes
            - /srv/lmdb/proteins:/home/n4j/neo4japp/services/annotations/lmdb/proteins
            - /srv/lmdb/species:/home/n4j/neo4japp/services/annotations/lmdb/species
            - /srv/lmdb/phenotypes:/home/n4j/neo4japp/services/annotations/lmdb/phenotypes
        networks:
            - backend

    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
        environment:
            - discovery.type=single-node
            - http.max_content_length=200mb  #allow 200mb of content to be sent for indexing
            - bootstrap.memory_lock=true
            - xpack.graph.enabled=false
            - xpack.watcher.enabled=false
            - xpack.license.self_generated.type=basic
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            - backend

    kibana:
        container_name: kibana
        image: docker.elastic.co/kibana/kibana:7.2.0
        ports:
            - "5601:5601"
        environment:
            SERVER_NAME: localhost
            ELASTICSEARCH_URL: http://elasticsearch:9200
        networks:
            - backend
        depends_on:
            - elasticsearch

networks:
    backend:
