# local development overrides

version: '3.5'

services:

    appserver:
        container_name: n4j-appserver
        command: ['bin/start-dev']
        build: ./appserver
        ports:
            - "5000:5000"
        environment:
            - FLASK_DEBUG=1
            - FLASK_APP=app
            - FLASK_APP_CONFIG=Development
