# local development overrides

version: '3.5'

services:
    pgdatabase:
        command: postgres -c max_wal_size=2GB -c log_statement='all'
        container_name: pg-database
        image: postgres:10.2
        networks:
            - backend
        ports:
            - "5431:5432"
        volumes:
            -  ./postgres/db:/var/lib/postgresql/data

    appserver:
        container_name: n4j-appserver
        command: ['bin/wait-for-postgres', 'bin/start-dev']
        build: ./appserver
        ports:
            - "5000:5000"
        environment:
            - NEO4J_HOST=bolt://n4j-database:7687
            - NEO4J_USER=neo4j
            - FLASK_DEBUG=1
            - FLASK_APP=app
            - FLASK_APP_CONFIG=Development
            - POSTGRES_HOST=pgdatabase
            # Postgres defaults
            - POSTGRES_PORT=5432
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        networks:
            - frontend
            - backend
        volumes:
            - ./appserver:/home/n4j
        depends_on:
            - database
            - pgdatabase
        stdin_open: true
        tty: true

    database:
        container_name: n4j-database
        environment:
            - NEO4J_AUTH=none
        image: neo4j:3.5.14
        ports:
            - "7474:7474"
            - "7687:7687"
        networks:
            - backend
        volumes:
            - ./db/data:/data
            - ./db/logs:/logs
            - ./db/plugins:/plugins

    elasticsearch:
        container_name: n4j-elasticsearch
        build:
            ./elasticsearch
        environment:
            - discovery.type=single-node
            - http.max_content_length=200mb
            - bootstrap.memory_lock=true
            - xpack.graph.enabled=false
            - xpack.watcher.enabled=false
            - xpack.license.self_generated.type=basic
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ./elasticsearch/esdata:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            - backend

networks:
    frontend:
    backend:
