version: "3.9"
name: "***ARANGO_DB_NAME***-local"
# This configuration includes two way volume binding for working with locally modified source code

x-appserver-mounts: &appserver-mounts
  volumes:
    - ./appserver:/home/n4j
    - lmdb:/home/n4j/neo4japp/services/annotations/lmdb

services:
  migrate:
    extends:
      file: docker-compose.yml
      service: migrate
    volumes:
      - ./migrations:/home/n4j

  appserver:
    <<: *appserver-mounts
    extends:
      file: docker-compose.yml
      service: appserver

  worker:
    <<: *appserver-mounts
    extends:
      file: docker-compose.yml
      service: worker

  webserver:
    extends:
      file: docker-compose.yml
      service: webserver
    volumes:
      - ./client:/app
      # https://jdlm.info/articles/2019/09/06/lessons-building-node-app-docker.html
      # Helps not overwrite the node_modules with host
      - node_modules:/app/node_modules

  statistical-enrichment:
    extends:
      file: docker-compose.yml
      service: statistical-enrichment
    volumes:
      - ./statistical-enrichment:/home/user

  cache-invalidator:
    extends:
      file: docker-compose.yml
      service: cache-invalidator
    volumes:
      - ./cache-invalidator:/app

  pdfparser:
    extends:
      file: docker-compose.yml
      service: pdfparser

  pgdatabase:
    extends:
      file: docker-compose.yml
      service: pgdatabase

  graphdatabase:
    extends:
      file: docker-compose.yml
      service: graphdatabase

  arangodb:
    extends:
      file: docker-compose.yml
      service: arangodb
    volumes:
      - ./arangodb/bin:/home/dbuser/bin # the /home/dbuser directory is setup in the Dockerfile
      - ./arangodb/data/${COMPOSE_PROJECT_NAME}:/var/lib/arangodb3
      - ./arangodb/apps/${COMPOSE_PROJECT_NAME}:/var/lib/arangodb3-apps

  redis:
    extends:
      file: docker-compose.yml
      service: redis

  elasticsearch:
    extends:
      file: docker-compose.yml
      service: elasticsearch

  #  Middlewares
  kibana:
    extends:
      file: docker-compose.yml
      service: kibana

  logstash:
    extends:
      file: docker-compose.yml
      service: logstash

  metricbeat:
    extends:
      file: docker-compose.yml
      service: metricbeat

  filebeat:
    extends:
      file: docker-compose.yml
      service: filebeat

volumes:
  node_modules:
  lmdb:

networks:
  frontend:
  backend:
  elastic:
