#!/bin/bash

echo "Setting environment variables..."

export NEO4J_PWD=
# bolt://<ip>:7687
export NEO4J_INSTANCE_URI=
export NEO4J_USERNAME=
export AZURE_ACCOUNT_STORAGE_NAME=
export AZURE_ACCOUNT_STORAGE_KEY=
