directories:
  dataDirectory: ../../data
  downloadDirectory: ../../data/download
  processedDirectory: ../../data/processed
  changelogsDirectory: ../../data/changelogs

neo4j:
  uri: bolt://localhost:7687
  user: neo4j
  password: rcai
