config:
  BinderHub:
    auth_enabled: true
    hub_url: https://jupyter-demo.***ARANGO_DB_NAME***.bio
    use_registry: true
    image_prefix: gcr.io/able-goods-221820/binderhub-demo
  GitHubRepoProvider:
    access_token: # Get this value from our existing Binderhub release (you can find it in the helm chart)
    banned_specs:
      - ^(?!SBRG/|\.).*

service:
  type: ClusterIP

jupyterhub:
  proxy:
    service:
      type: ClusterIP
    https:
      enabled: true
      type: letsencrypt
  ingress:
    enabled: true
    hosts:
      - jupyter-demo.***ARANGO_DB_NAME***.bio
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    tls:
      - secretName: jupyter-demo-***ARANGO_DB_NAME***-bio-tls
        hosts:
          - jupyter-demo.***ARANGO_DB_NAME***.bio
  cull:
    # Since we're using authenticated users, don't cull them. We would set this to true if we were using temp users.
    users: false
    timeout: 1800
    removeNamedServers: true
  hub:
    allowNamedServers: true
    namedServerLimitPerUser: 5
    shutdownOnLogout: true
    redirectToServer: false
    config:
      BinderSpawner:
        auth_enabled: true
      JupyterHub:
        authenticator_class: google
      Authenticator:
        allowed_users:
          - e4sanchez@@eng.ucsd.edu # Ethan
          # You can add more users here
      GoogleOAuthenticator:
        client_id: # Get this value from the Google Cloud Console
        client_secret: # Get this value from the Google Cloud Console
        oauth_callback_url: https://jupyter-demo.***ARANGO_DB_NAME***.bio/hub/oauth_callback
        login_service: Google
    services:
      binder:
        oauth_client_id: service-binderhub
        oauth_no_confirm: true
        oauth_redirect_uri: "https://binder-demo.***ARANGO_DB_NAME***.bio/oauth_callback"
    loadRoles:
      user:
        scopes:
          - self
          - "access:services"
  singleuser:
    # to make notebook servers aware of hub
    cmd: jupyterhub-singleuser

ingress:
  enabled: true
  https:
    enabled: true
    type: letsencrypt
  hosts:
    - binder-demo.***ARANGO_DB_NAME***.bio
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    - secretName: binder-demo-***ARANGO_DB_NAME***-bio-tls
      hosts:
        - binder-demo.***ARANGO_DB_NAME***.bio

registry:
  password: # You can find this defined in the existing deployment
  url: https://gcr.io
