version: '3.5'

services:
    production-nginx-container:
        container_name: 'production-nginx-container'
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./production.conf:/etc/nginx/conf.d/default.conf
            - ./production-site:/usr/share/nginx/html
            - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
            - /docker-volumes/etc/letsencrypt/live/kg.***ARANGO_DB_NAME***.bio/fullchain.pem:/etc/letsencrypt/live/kg.***ARANGO_DB_NAME***.bio/fullchain.pem
            - /docker-volumes/etc/letsencrypt/live/kg.***ARANGO_DB_NAME***.bio/privkey.pem:/etc/letsencrypt/live/kg.***ARANGO_DB_NAME***.bio/privkey.pem
        networks:
            - docker-network

networks:
    docker-network:
        driver: bridge
