- name: Create dh-param directory
  become: yes
  become_user: root
  file:
    path: "{{ dh_param_dir }}"
    state: directory

- name: Generate dh-param
  become: yes
  become_user: root
  shell: openssl dhparam -out "{{ dh_param_dir }}/dhparam-2048.pem" 2048