- name: Create dh-param directory
  become: yes
  become_user: ***ARANGO_USERNAME***
  file:
    path: "{{ dh_param_dir }}"
    state: directory

- name: Generate dh-param
  become: yes
  become_user: ***ARANGO_USERNAME***
  shell: openssl dhparam -out "{{ dh_param_dir }}/dhparam-2048.pem" 2048