- name: Create dh-param directory
  become: yes
  become_user: root
  file:
    path: "{{ dh_param_dir }}"
    state: directory

- name: Check if dh-param exists
  become: true
  stat:
    path: "{{ dh_param_dir }}/dhparam-2048.pem"
  register: dh_param_pem

- name: Generate dh-param
  become: yes
  become_user: root
  shell: openssl dhparam -out "{{ dh_param_dir }}/dhparam-2048.pem" 2048
  when: not dh_param_pem.stat.exists
