import os

FILE_INDEX_ID = os.environ.get('ELASTIC_FILE_INDEX_ID')
ELASTICSEARCH_HOSTS = os.environ.get('ELASTICSEARCH_HOSTS')
ATTACHMENT_PIPELINE_ID = 'attachment'

BULK_INDEX_OP = 'BULK_INDEX'
BULK_UPDATE_OP = 'BULK_UPDATE'
BULK_DELETE_OP = 'BULK_DELETE'
