#!/bin/sh

# Path from shell to folder containing this file
__dir__="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# Runs linting on only files that are staged
staged_files=$(getStaged migrations '\.(py)$')

# Turn debugging on by the flag
if [[ -n $DEBUG_HOOKS ]];
then
  echo "> 🐛 flake8 version:"
  image_hash=$(docker build -q -f $__dir__/flake8_Dockerfile $__dir__)
  docker run -rm $image_hash --version
fi

# shellcheck disable=SC2236
if [[ -n $staged_files ]];
then
   (
    echo "> 🌽 Running flake8..."
    image_hash=$(docker build -q -f $__dir__/flake8_Dockerfile $__dir__)
    echo ${staged_files} | \
      xargs docker run --rm \
      -v $(pwd)/migrations:/apps \
      $image_hash
  )
else
  echo "> Skipping python files check for migrations..."
fi
