## This is an example values files for installing Lifelike Helm chart
## connecting to external existing database services
## instead of installing the embedded subcharts (postgres, arangodb and elasticsearch)


# Disable the embedded PostgreSQL subchart
postgresql:
  enabled: false
# Configure external psostgres database
postgresqlExternal:
  host: postgres.local
  port: 5432
  user: postgres
  database: postgres
  password: password

# Disable embedded ArangoDB subchart
arangodb:
  enabled: false
# Configure external ArangoDB database
arangodbExternal:
  host: arangodb.local
  port: 7687
  user: arangodb
  password: password

# Disable embedded Elasticsearch subchart
elasticsearch:
  enabled: false
elasticsearchExternal:
  host: elasticsearch.local
  port: 9200
  user: "elastic"
  password: "password"
