# Overrides base docker-compose.yml file
# to add stateful backing services (e.g. databases)
version: "3.8"

services:
  # PostgreSQL database
  postgres:
    image: postgres:18.2
    restart: unless-stopped
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-q"]
      start_period: 10s

  ## ArangoDB graph database
  arangodb:
    build:
      # Note that this Dockerfile simply adds a user directory and installs the helper scripts into it, and then executes the default arango
      # entrypoint as normal.
      context: ../arangodb
      dockerfile: Dockerfile
    container_name: arangodb
    environment:
      ARANGO_ROOT_PASSWORD: password
      LIFELIKE_DB_NAME: lifelike
    ports:
      - 8529:8529
    volumes:
      - ../arangodb/bin:/home/dbuser/bin # the /home/dbuser directory is setup in the Dockerfile
      - ../arangodb/data:/var/lib/arangodb3
      - ../arangodb/apps:/var/lib/arangodb3-apps

  ## Ekasticsearch search engine
  elasticsearch:
    container_name: elasticsearch
    build:
      dockerfile: Dockerfile
      context: ../elasticsearch
    environment:
      - discovery.type=single-node
      - http.max_content_length=200mb #allow 200mb of content to be sent for indexing
      - bootstrap.memory_lock=true
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - xpack.license.self_generated.type=basic
    volumes:
      - ../elasticsearch:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:9200/_cluster/health"]
      start_period: 1m

  redis:
    image: redis:6-alpine
    restart: unless-stopped
    container_name: redis
    ports:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  appserver:
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=postgres
      # Arango
      - ARANGO_HOST=http://arangodb:8529
      - ARANGO_USERNAME=root
      - ARANGO_PASSWORD=password
      - ARANGO_DB_NAME=lifelike
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - arangodb
      - elasticsearch

  statistical-enrichment:
    environment:
      # Arango
      - ARANGO_HOST=http://arangodb:8529
      - ARANGO_USERNAME=root
      - ARANGO_PASSWORD=password
      - ARANGO_DB_NAME=lifelike
      - REDIS_HOST=redis
    depends_on:
      - arangodb
      - redis

  cache-invalidator:
    environment:
      # Arango
      - ARANGO_HOST=http://arangodb:8529
      - ARANGO_USERNAME=root
      - ARANGO_PASSWORD=password
      - ARANGO_DB_NAME=lifelike
      - REDIS_HOST=redis
    depends_on:
      - arangodb
      - redis

volumes:
  postgres:
  arangodb:
  elasticsearch:
