version: "3.9"

x-appserver: &appserver
  build: ../appserver
  environment:
    # Log Services
    - FORMAT_AS_JSON=false
    # Flask
    - FLASK_APP=app
    - FLASK_APP_CONFIG=Development
    - FLASK_DEBUG=1
    - FLASK_ENV=development
    # Postgres
    - POSTGRES_HOST=pgdatabase
    - POSTGRES_PORT=5432
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=postgres
    # ElasticSearch
    - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    - ELASTIC_FILE_INDEX_ID=file_dev
    # Neo4j
    - NEO4J_SCHEME=bolt
    - NEO4J_HOST=graphdatabase
    - NEO4J_AUTH=neo4j/password
    - NEO4J_PORT=7687
    # Redis
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - REDIS_PASSWORD=password
    - REDIS_SSL=false
    # StatisticalEnrichment
    - SE_HOST=statistical-enrichment
    - SE_PORT=5010
    # Other
    - DOMAIN=http://localhost:4200
    - LMDB_HOME_FOLDER=/home/n4j/neo4japp/services/annotations/lmdb/
    - ASSETS_FOLDER=/home/n4j/assets/
  volumes:
    - ../appserver:/home/n4j
    - lmdb:/home/n4j/neo4japp/services/annotations/lmdb
  depends_on:
    - postgres
    - neo4j
    - elasticsearch
    - redis
    - pdfparser

services:
  appserver:
    <<: *appserver
    ports:
      - 5000:5000
    networks:
      - backend
      - frontend

  worker:
    <<: *appserver
    command: flask rq worker
    networks:
      - backend

  webserver:
    build:
      context: ../client
      dockerfile: Dockerfile
      target: angular-deps
    command: yarn dev-start
    volumes:
      - ../client:/app
      # https://jdlm.info/articles/2019/09/06/lessons-building-node-app-docker.html
      # Helps not overwrite the node_modules with host
      - /app/node_modules
    ports:
      - 4200:4200
    networks:
      - frontend

  statistical-enrichment:
    build: ../statistical-enrichment
    ports:
      - 5010:5010
    environment:
      # Flask
      - FLASK_APP=statistical_enrichment
      - FLASK_APP_CONFIG=Development
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      # Neo4j
      - NEO4J_SCHEME=bolt
      - NEO4J_HOST=graphdatabase
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PORT=7687
      # Redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password
      - REDIS_SSL=false
    # Allow debugging w/ IPython or pdb
    stdin_open: true
    tty: true
    # End debugging section
    volumes:
      - ../statistical-enrichment:/home/user
    networks:
      - backend
    depends_on:
      - graphdatabase
      - redis

  cache-invalidator:
    build: ../cache-invalidator
    environment:
      - LOG_LEVEL=debug
      # Neo4j
      - NEO4J_SCHEME=bolt
      - NEO4J_HOST=graphdatabase
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PORT=7687
      # Redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password
      - REDIS_SSL=false
    volumes:
      - ../cache-invalidator:/app
    networks:
      - backend
    depends_on:
      - redis
      - graphdatabase

  pdfparser:
    image: ghcr.io/sbrg/***ARANGO_DB_NAME***-pdfparser:latest
    ports:
      - 7600:7600
    # tty: true - this is a hack for grizzly as it expects input;
    # without it, container will exit right away due to docker not accepting input by default
    tty: true
    networks:
      - backend

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - backend

  neo4j:
    image: neo4j:4.4-community
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4JLABS_PLUGINS=["apoc"]
    ports:
      - 7474:7474
      - 7687:7687
    networks:
      - backend

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass password
    networks:
      - backend

  elasticsearch:
    build:
      dockerfile: Dockerfile
      context: elasticsearch
    environment:
      - discovery.type=single-node
      - http.max_content_length=200mb #allow 200mb of content to be sent for indexing
      - bootstrap.memory_lock=true
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - xpack.license.self_generated.type=basic
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - backend

volumes:
  lmdb:

networks:
  frontend:
  backend:
