apiVersion: v1
kind: Secret
metadata:
  name: {{ template "***ARANGO_DB_NAME***.fullname" . }}
  labels:
    {{- include "***ARANGO_DB_NAME***.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
type: Opaque
data:
  POSTGRES_PASSWORD: {{ include "***ARANGO_DB_NAME***.postgresqlPassword" . | trim | b64enc | quote }}
