- name: Create Nginx Directory
  file:
    path: "{{ nginx_conf_dir }}"
    state: directory

- name: Check if TLS certificate exists
  become: true
  stat:
    path: "{{ certbot_conf_dir }}/live/{{ server_name }}"
  register: certbot_certs

- name: Copy nginx certbot config
  template:
    src: templates/nginx-certbot.conf
    dest: "{{ nginx_conf_dir }}/{{ server_name }}.conf"
  when: not certbot_certs.stat.exists

- name: Start nginx container
  docker_container:
    name: "{{ nginx_hostname }}"
    image: "{{ nginx_image }}"
    ports:
      - 80:80
    volumes:
      - "{{ nginx_conf_dir }}/:/etc/nginx/conf.d/:ro"
      - "{{ certbot_conf_dir }}/:/etc/letsencrypt/"
      - "{{ certbot_conf_dir }}/www/:/var/www/certbot/"
  when: not certbot_certs.stat.exists

- name: Issue certificate with certbot command
  docker_container:
    name: "{{ certbot_hostname }}"
    image: "{{ certbot_image }}"
    volumes:
      - "{{ certbot_conf_dir }}/:/etc/letsencrypt/"
      - "{{ certbot_conf_dir }}/www/:/var/www/certbot/"
    command: certonly --webroot --email {{ certbot_email }} --agree-tos --webroot-path=/var/www/certbot/ -d {{ server_name }}
  when: not certbot_certs.stat.exists

- name: Start nginx container
  docker_container:
    name: "{{ nginx_hostname }}"
    state: absent
