- name: Configure server with Docker
  hosts: webservers
  become: yes
  tasks:
    - name: Assure old docker isn't installed
      apt:
        name: "{{ packages }}"
        update_cache: yes
        state: absent
      vars:
        packages:
            - docker
            - docker-engine
            - docker.io
            - containerd

    - name: Install dependencies
      apt:
        update_cache: yes
        pkg:
            - apt-transport-https
            - ca-certificates
            - curl
            - software-properties-common
            - gnupg-agent
            - python3-setuptools

    - name: Add Docker repo GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repoistory
      apt_repository:
        repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable'
        state: present
        update_cache: yes

    - name: Install Docker and Docker Compose
      apt:
        pkg:
            - docker-ce
            - docker-ce-cli
            - containerd.io
            - docker-compose

    - name: Add Docker Group
      group:
        name: "docker"
        state: present

    - name: Add user "ubuntu" to "docker" group
      user:
        name: "ubuntu"
        group: "docker"
        append: yes
