version: '3.8'

services:
    appserver:
        ports:
            - 5000:5000
        env_file:
            - ./.env
        volumes:
            - ${LMDB_DIR:-/home/ansible/lmdb}:/home/n4j/neo4japp/services/annotations/lmdb
        networks:
            - frontend
            - backend

    webserver:
        ports:
            - 80:80
            - 443:443
        networks:
            - frontend

networks:
    frontend:
    backend:
