version: '3.8'

services:
    appserver:
        image: ${REGISTRY:-***ARANGO_DB_NAME***.azurecr.io}/kg-appserver:${GITHUB_HASH:-latest}

    cache-invalidator:
        image: ${REGISTRY:-***ARANGO_DB_NAME***.azurecr.io}/kg-cache-service:${GITHUB_HASH:-latest}

    redis:
        image: redis:6.0.3-alpine

    webserver:
        image: ${REGISTRY:-***ARANGO_DB_NAME***.azurecr.io}/kg-webserver:${GITHUB_HASH:-latest}

    pdfparser:
        image: ${REGISTRY:-***ARANGO_DB_NAME***.azurecr.io}/kg-pdfparser:latest

    statistical-enrichment:
        image: ${REGISTRY:-***ARANGO_DB_NAME***.azurecr.io}/kg-statistical-enrichment:${GITHUB_HASH:-latest}
