version: '3.8'

services:
    appserver:
        ports:
            - 5000:5000
        env_file:
            - ./.env
        volumes:
            - ${LMDB_DIR:-/home/ansible/lmdb}:/home/n4j/neo4japp/services/annotations/lmdb
        networks:
            - frontend
            - backend

    webserver:
        ports:
            - 80:80
            - 443:443
        volumes:
            - ${DH_PARAM_FILE:-/home/ansible/dh-param/dhparam-2048.pem}:/etc/ssl/certs/dhparam-2048.pem
            - ${CERTBOT_CERT_DIR:-/home/ansible/certbot/etc/letsencrypt/live}/${DOMAIN}/fullchain.pem:/etc/letsencrypt/live/${DOMAIN}/fullchain.pem
            - ${CERTBOT_CERT_DIR:-/home/ansible/certbot/etc/letsencrypt/live}/${DOMAIN}/privkey.pem:/etc/letsencrypt/live/${DOMAIN}/privkey.pem
        networks:
            - frontend

    nlpapi:
        expose:
            - 5001
        env_file:
            - ./.env
        volumes:
            - ${NLP_DIR:-/home/ansible/models}:/models
        networks:
            - backend

    cache-invalidator:
        env_file:
            - ./.env
        networks:
            - backend

    redis:
        networks:
            - backend

networks:
    frontend:
    backend:
