version: '3.8'

services:
    appserver:
        ports:
            - 5000:5000
        env_file:
            - ./.env
        volumes:
            - ${LMDB_DIR:-/home/ansible/lmdb}:/home/n4j/neo4japp/services/annotations/lmdb
        networks:
            - frontend
            - backend

    webserver:
        ports:
            - 80:80
            - 443:443
        networks:
            - frontend
        depends_on:
            - appserver

    statistical-enrichment:
        expose:
            - 5010
        env_file:
            - ./.env
        networks:
            - backend

    pdfparser:
        ports:
            - "7600:7600"
        # tty: true - this is a hack for grizzly as it expects input;
        # without it, container will exit right away due to docker not accepting input by default
        tty: true
        networks:
            - backend

    cache-invalidator:
        env_file:
            - ./.env
        networks:
            - backend

    redis:
        command: redis-server --requirepass ${REDIS_PASSWORD}
        networks:
            - backend

networks:
    frontend:
    backend:
