version: '3.8'

services:
    appserver:
        ports:
            - 5000:5000
        env_file:
            - ./.env
        volumes:
            # Service account file needs access to Google Cloud Storage (Bucket)
            - ${GCP_SERVICE_ACCOUNT:-/home/ansible/ansible_service_account.json}:/home/n4j/ansible_service_account.json
            - ${LMDB_DIR:-/home/ansible/lmdb}:/home/n4j/neo4japp/services/annotations/lmdb
        networks:
            - frontend
            - backend

    webserver:
        ports:
            - 80:80
            - 443:443
        networks:
            - frontend

    pdfparser:
        ports:
            - "7600:7600"
        # tty: true - this is a hack for grizzly as it expects input;
        # without it, container will exit right away due to docker not accepting input by default
        tty: true
        networks:
            - backend

    cache-invalidator:
        env_file:
            - ./.env
        networks:
            - backend

    redis:
        networks:
            - backend

networks:
    frontend:
    backend: