version: '3.8'

services:
    appserver:
        image: ${REGISTRY:-lifelike.azurecr.io}/kg-appserver:${GITHUB_HASH:-latest}

    cache-invalidator:
        image: ${REGISTRY:-lifelike.azurecr.io}/kg-cache-service:${GITHUB_HASH:-latest}

    redis:
        image: redis:6.0.3-alpine

    webserver:
        image: ${REGISTRY:-lifelike.azurecr.io}/kg-webserver:${GITHUB_HASH:-latest}

    pdfparser:
        image: ${REGISTRY:-lifelike.azurecr.io}/kg-pdfparser:latest