#!/bin/sh

# Runs linting on only files that are staged
staged_files=$(getStaged annotator '\.(py)$')

# Turn debugging on by the flag
if [[ -n $DEBUG_HOOKS ]];
then
  echo "> 🐛 flake8 version:"
  docker exec annotator flake8 --version
  echo "> 🐛 mypy version:"
  docker exec annotator mypy --version
  echo "> 🐛 pycodestyle version:"
  docker exec annotator pycodestyle --version
fi

# shellcheck disable=SC2236
if [[ -n $staged_files ]];
then
  (
    echo "> 🌽 Running flake8..."
    echo ${staged_files} | xargs docker exec annotator flake8
  ) && (
    echo "> 🥧 Running mypy..."
    echo ${staged_files} | xargs docker exec annotator mypy
  ) && (
    echo "> 🐍 Running pycodestyle..."
    echo ${staged_files} | xargs docker exec annotator pycodestyle
  )
else
  echo "> Skipping..."
fi
