clean:
	echo "Cleaning up secrets..."
	echo "> Removing ansible_service_account.json"
	rm -rf ansible_service_account.json
	echo "> Removing servers.json"
	rm -rf servers.json
	echo "> Removing LMDB directory"
	rm -rf lmdb