version: "3.8"

services:
  elasticsearch:
    container_name: elasticsearch
    build:
      context: ../elasticsearch
      dockerfile: Dockerfile
    environment:
      - discovery.type=single-node
      - http.max_content_length=200mb #allow 200mb of content to be sent for indexing
      - bootstrap.memory_lock=true
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - xpack.license.self_generated.type=basic
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.10.1
    ports:
      - "5601:5601"
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch

  logstash:
    container_name: logstash
    build:
      context: ../logstash
      dockerfile: Dockerfile
    volumes:
      - ../logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ../logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - 5044:5044
      - 9600:9600
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
