apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "***ARANGO_DB_NAME***.fullname" . }}-fontend
  labels:
    {{- include "***ARANGO_DB_NAME***.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  selector:
    matchLabels:
      {{- include "***ARANGO_DB_NAME***.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  replicas: {{ .Values.frontend.replicaCount }}
  template:
    metadata:
      annotations: {{ toYaml .Values.frontend.podAnnotations | nindent 8 }}
      labels:
        {{- include "***ARANGO_DB_NAME***.selectorLabels" . | nindent 8 }}
        {{- if .Values.frontend.podLabels }}
        {{ toYaml .Values.frontend.podLabels | nindent 8 }}
        {{- end }}
        app.kubernetes.io/component: frontend
    spec:
      {{- if .Values.frontend.affinity }}
      affinity: {{ toYaml .Values.frontend.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.frontend.nodeSelector }}
      nodeSelector: {{ toYaml .Values.frontend.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.frontend.tolerations }}
      tolerations: {{ toYaml .Values.frontend.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.frontend.schedulerName }}
      schedulerName: "{{ .Values.frontend.schedulerName }}"
      {{- end }}
      {{- if .Values.frontend.image.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.frontend.image.imagePullSecrets | nindent 6 }}
      {{- end }}
      securityContext:
        {{- $securityContext := .Values.frontend.podSecurityContext | default (dict) | deepCopy }}
        {{- if .Values.frontend.defaultPodSecurityContext.enabled }}
        {{- $securityContext = $securityContext | merge (omit .Values.frontend.defaultPodSecurityContext "enabled") }}
        {{- end }}
        {{- toYaml $securityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}-frontend
        image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default (printf "%s" .Chart.AppVersion) }}
        imagePullPolicy: {{ .Values.frontend.image.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.frontend.service.port }}
        env:
        {{- range $envName, $envValue := .Values.frontend.extraEnv }}
        - name: {{ $envName }}
          value: {{ $envValue | quote }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: {{ default "/" .Values.frontend.livenessProbe.path }}
            port: {{ .Values.frontend.service.port }}
            scheme: HTTP
          failureThreshold: {{ .Values.frontend.livenessProbe.failureThreshold }}
          initialDelaySeconds: {{ .Values.frontend.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.frontend.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.frontend.livenessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.frontend.livenessProbe.timeoutSeconds }}
        readinessProbe:
          httpGet:
            path: {{ default "/" .Values.frontend.readinessProbe.path "/" }}
            port: {{ .Values.frontend.service.port }}
            scheme: HTTP
          failureThreshold: {{ .Values.frontend.readinessProbe.failureThreshold }}
          initialDelaySeconds: {{ .Values.frontend.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.frontend.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.frontend.readinessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.frontend.readinessProbe.timeoutSeconds }}                    
        resources: {{ toYaml .Values.frontend.resources | nindent 10 }}
