""" Add author for directory

Revision ID: 36d25e171658
Revises: cc345dcad75c
Create Date: 2020-07-22 19:25:59.212662

"""
from alembic import context
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '36d25e171658'
down_revision = 'cc345dcad75c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('directory', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f('fk_directory_user_id_appuser'),
        'directory', 'appuser', ['user_id'], ['id']
    )
    # ### end Alembic commands ###
    if context.get_x_argument(as_dictionary=True).get('data_migrate', None):
        data_upgrades()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_directory_user_id_appuser'), 'directory', type_='foreignkey')
    op.drop_column('directory', 'user_id')
    # ### end Alembic commands ###
    # NOTE: In practice perfect downgrades are difficult and in some cases
    # impossible! It is more practical to use database backups/snapshots to
    # "downgrade" the database. Changes to the database that we intend to
    # push to production should always be added to a NEW migration.
    # (i.e. "downgrade forward"!)


def data_upgrades():
    """Add optional data upgrade migrations here"""
    pass


def data_downgrades():
    """Add optional data downgrade migrations here"""
    pass
