"""Drop access_control_policy table

Revision ID: 6b7a2da00472
Revises: 51738a88de73
Create Date: 2022-01-18 22:26:50.926172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b7a2da00472'
down_revision = '51738a88de73'
branch_labels = None
depends_on = None


def upgrade():
    op.drop_index('ix_acp_principal_key', table_name='access_control_policy')
    op.drop_index('ix_acp_asset_key', table_name='access_control_policy')
    op.drop_table('access_control_policy')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'access_control_policy',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('action', sa.String(length=50), nullable=False),
        sa.Column('asset_type', sa.String(length=200), nullable=False),
        sa.Column('asset_id', sa.Integer(), nullable=True),
        sa.Column('principal_type', sa.String(length=50), nullable=False),
        sa.Column('principal_id', sa.Integer(), nullable=True),
        sa.Column('rule_type', sa.Enum('ALLOW', 'DENY', name='accessruletype'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_acp_asset_key', 'access_control_policy', ['asset_type', 'asset_id'], unique=False)  # noqa
    op.create_index('ix_acp_principal_key', 'access_control_policy', ['principal_type', 'principal_id'], unique=False)  # noqa
