"""empty message

Revision ID: 78031695e8fc
Revises: 3d2612106247
Create Date: 2020-06-04 20:16:19.483699

"""
from alembic import context
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '78031695e8fc'
down_revision = '3d2612106247'
branch_labels = None
depends_on = None


def upgrade():
    access = postgresql.ENUM('READ', 'WRITE', name='accessactiontype')
    access.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('access_control_policy', 'action',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('READ', 'WRITE', name='accessactiontype'),
               existing_nullable=False,
               postgresql_using='action::accessactiontype')
    # ### end Alembic commands ###
    if context.get_x_argument(as_dictionary=True).get('data_migrate', None):
        data_upgrades()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('access_control_policy', 'action',
               existing_type=sa.Enum('READ', 'WRITE', name='accessactiontype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
    # NOTE: In practice perfect downgrades are difficult and in some cases
    # impossible! It is more practical to use database backups/snapshots to
    # "downgrade" the database. Changes to the database that we intend to
    # push to production should always be added to a NEW migration.
    # (i.e. "downgrade forward"!)


def data_upgrades():
    """Add optional data upgrade migrations here"""
    pass


def data_downgrades():
    """Add optional data downgrade migrations here"""
    pass
