"""empty message

Revision ID: b6f5fafab2e2
Revises: 42cb9144dd13
Create Date: 2021-05-03 10:02:28.282328

"""
from alembic import context
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b6f5fafab2e2'
down_revision = '42cb9144dd13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('access_control_policy', 'action',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('READ', 'WRITE', name='accessactiontype'),
               existing_nullable=False)
    op.alter_column('file_annotations_version', 'cause',
               existing_type=postgresql.ENUM('USER', 'USER_REANNOTATION', 'SYSTEM_REANNOTATION', name='annotationcause'),
               type_=sa.Enum('USER', 'USER_REANNOTATION', 'SYSTEM_REANNOTATION', name='annotationchangecause'),
               existing_nullable=False)
    # ### end Alembic commands ###
    if context.get_x_argument(as_dictionary=True).get('data_migrate', None):
        data_upgrades()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_annotations_version', 'cause',
               existing_type=sa.Enum('USER', 'USER_REANNOTATION', 'SYSTEM_REANNOTATION', name='annotationchangecause'),
               type_=postgresql.ENUM('USER', 'USER_REANNOTATION', 'SYSTEM_REANNOTATION', name='annotationcause'),
               existing_nullable=False)
    op.alter_column('access_control_policy', 'action',
               existing_type=sa.Enum('READ', 'WRITE', name='accessactiontype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
    # NOTE: In practice perfect downgrades are difficult and in some cases
    # impossible! It is more practical to use database backups/snapshots to
    # "downgrade" the database. Changes to the database that we intend to
    # push to production should always be added to a NEW migration.
    # (i.e. "downgrade forward"!)


def data_upgrades():
    """Add optional data upgrade migrations here"""
    pass


def data_downgrades():
    """Add optional data downgrade migrations here"""
    pass
