"""empty message

Revision ID: c5d1a5f421ae
Revises: 6f0a61388077
Create Date: 2020-06-04 14:12:35.993859

"""
from alembic import context
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5d1a5f421ae'
down_revision = '6f0a61388077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotation_style',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('color', sa.String(length=8), nullable=False),
    sa.Column('icon_code', sa.String(length=32), nullable=True),
    sa.Column('style_border', sa.String(length=8), nullable=True),
    sa.Column('style_background', sa.String(length=8), nullable=True),
    sa.Column('style_color', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_annotation_style'))
    )
    # ### end Alembic commands ###
    if context.get_x_argument(as_dictionary=True).get('data_migrate', None):
        data_upgrades()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('annotation_style')
    # ### end Alembic commands ###
    # NOTE: In practice perfect downgrades are difficult and in some cases
    # impossible! It is more practical to use database backups/snapshots to
    # "downgrade" the database. Changes to the database that we intend to
    # push to production should always be added to a NEW migration.
    # (i.e. "downgrade forward"!)


def data_upgrades():
    """Add optional data upgrade migrations here"""
    pass


def data_downgrades():
    """Add optional data downgrade migrations here"""
    pass
