"""Delete worksheets table

Revision ID: cf9f210458c8
Revises: 85062d2a244a
Create Date: 2022-01-14 01:11:32.889812

"""
from alembic import context
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cf9f210458c8'
down_revision = '85062d2a244a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_worksheets_content_id', table_name='worksheets')
    op.drop_table('worksheets')
    # ### end Alembic commands ###
    if context.get_x_argument(as_dictionary=True).get('data_migrate', None):
        data_upgrades()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worksheets',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('filename', sa.VARCHAR(length=200),
                              autoincrement=False, nullable=False),
                    sa.Column('sheetname', sa.VARCHAR(length=200),
                              autoincrement=False, nullable=False),
                    sa.Column('neo4j_node_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('creation_date', postgresql.TIMESTAMP(timezone=True),
                              autoincrement=False,
                              nullable=False),
                    sa.Column('content_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('modified_date', postgresql.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(
                        ['content_id'],
                        ['files_content.id'],
                        name='fk_worksheets_content_id_files_content',
                        ondelete='CASCADE'
                    ),
                    sa.PrimaryKeyConstraint('id', name='pk_worksheets'))
    op.create_index('ix_worksheets_content_id', 'worksheets', ['content_id'], unique=False)
    # ### end Alembic commands ###
    # NOTE: In practice perfect downgrades are difficult and in some cases
    # impossible! It is more practical to use database backups/snapshots to
    # "downgrade" the database. Changes to the database that we intend to
    # push to production should always be added to a NEW migration.
    # (i.e. "downgrade forward"!)


def data_upgrades():
    """Add optional data upgrade migrations here"""
    pass


def data_downgrades():
    """Add optional data downgrade migrations here"""
    pass
