"""empty message

Revision ID: fad7f19902f2
Revises: dbf6e232ca92
Create Date: 2020-06-11 13:52:16.063099

"""
from alembic import context
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fad7f19902f2'
down_revision = 'dbf6e232ca92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('hexcode', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_color'))
    )
    op.create_table('domain_ul_rs_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=128), nullable=False),
    sa.Column('base_URL', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_domain_ul_rs_map'))
    )
    op.create_table('annotation_style',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('color', sa.Integer(), nullable=False),
    sa.Column('icon_code', sa.String(length=32), nullable=True),
    sa.Column('style_border', sa.Integer(), nullable=True),
    sa.Column('style_background', sa.Integer(), nullable=True),
    sa.Column('style_color', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['color'], ['color.id'], name=op.f('fk_annotation_style_color_color')),
    sa.ForeignKeyConstraint(['style_background'], ['color.id'], name=op.f('fk_annotation_style_style_background_color')),
    sa.ForeignKeyConstraint(['style_border'], ['color.id'], name=op.f('fk_annotation_style_style_border_color')),
    sa.ForeignKeyConstraint(['style_color'], ['color.id'], name=op.f('fk_annotation_style_style_color_color')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_annotation_style'))
    )
    # ### end Alembic commands ###
    if context.get_x_argument(as_dictionary=True).get('data_migrate', None):
        data_upgrades()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('annotation_style')
    op.drop_table('domain_ul_rs_map')
    op.drop_table('color')
    # ### end Alembic commands ###
    # NOTE: In practice perfect downgrades are difficult and in some cases
    # impossible! It is more practical to use database backups/snapshots to
    # "downgrade" the database. Changes to the database that we intend to
    # push to production should always be added to a NEW migration.
    # (i.e. "downgrade forward"!)


def data_upgrades():
    """Add optional data upgrade migrations here"""
    pass


def data_downgrades():
    """Add optional data downgrade migrations here"""
    pass
