apiVersion: v1
kind: Service
metadata:
  name: {{ include "***ARANGO_DB_NAME***.fullname" . }}-frontend
  labels: {{- include "***ARANGO_DB_NAME***.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
      protocol: TCP
      name: http
  selector: {{- include "***ARANGO_DB_NAME***.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
