# ========================================
# Runtime stage - NGINX
# ========================================
FROM nginx:1.25.1

# Copy nginx configuraiton template
COPY nginx.conf /etc/nginx/templates/default.conf.template
