version: "3.8"

services:
  ## Frontend web server
  webserver:
    image: ***ARANGO_DB_NAME***.azurecr.io/kg-webserver:latest
    restart: unless-stopped
    ports:
      - 80:80
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost"]
      interval: 10s
      timeout: 10s

  ## Backend application server
  appserver:
    image: ***ARANGO_DB_NAME***.azurecr.io/kg-appserver:latest
    restart: unless-stopped
    ports:
      - 5000:5000
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:5000/meta"]
      interval: 10s
      timeout: 5s

  ## Statistical enrichment service
  statistical-enrichment:
    image: ***ARANGO_DB_NAME***.azurecr.io/kg-statistical-enrichment:latest
    restart: unless-stopped
    ports:
      - 5000
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:5000/healthz"]
      interval: 5s
      timeout: 5s

  # Cache invalidation service
  cache-invalidator:
    image: ***ARANGO_DB_NAME***.azurecr.io/kg-cache-invalidator:latest
    restart: unless-stopped

networks:
  default:
    name: ***ARANGO_DB_NAME***
