- name: Assure old docker isn't installed
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: absent
  vars:
    packages:
      - docker
      - docker-engine
      - docker.io
      - containerd

- name: Install dependencies
  apt:
    update_cache: yes
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg-agent
      - python3-setuptools
      - python3-pip
      - python-pip
      # For docker login
      # https://forums.docker.com/t/docker-login-fails-with-error-message-error-saving-credentials-cannot-autolaunch-d-bus-without-x11-display/77789
      - gnupg2
      - pass

- name: Install Python dependencies
  pip:
    name:
      - docker
      - docker-compose

- name: Add Docker repo GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    state: present
    update_cache: yes

- name: Install Docker and Docker Compose
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose

- name: Add Docker Group
  group:
    name: "docker"
    state: present

- name: Add deploying user to "docker" group
  user:
    name: "{{ deploy_user }}"
    group: "docker"
    append: yes
