- include_vars: gcp_bucket_credentials.yml

- name: Install Python dependencies
  pip:
    name:
      - boto
      - sqlalchemy
      - google-cloud-storage
      - psycopg2-binary
    umask: "0022"
  become: True

- name: Create LMDB Database Directories
  file:
    path: "{{ lmdb_path }}/{{ item }}"
    state: directory
  loop:
    - chemicals
    - diseases
    - compounds
    - genes
    - phenotypes
    - proteins
    - species

- name: Fetch 'data.mdb' files
  gc_storage:
    bucket: lmdb_database
    object: "{{ item }}/data.mdb"
    dest: "{{ lmdb_path }}/{{ item }}/data.mdb"
    mode: get
    gs_access_key: "{{ gce_bucket_access_key }}"
    gs_secret_key: "{{ gce_bucket_secret_key }}"
    force: yes
  loop:
    - chemicals
    - diseases
    - compounds
    - genes
    - phenotypes
    - proteins
    - species

- name: Fetch 'lock.mdb' files
  gc_storage:
    bucket: lmdb_database
    object: "{{ item }}/lock.mdb"
    dest: "{{ lmdb_path }}/{{ item }}/lock.mdb"
    mode: get
    gs_access_key: "{{ gce_bucket_access_key }}"
    gs_secret_key: "{{ gce_bucket_secret_key }}"
    force: yes
  loop:
    - chemicals
    - diseases
    - compounds
    - genes
    - phenotypes
    - proteins
    - species

- name: Set user permission
  file:
    path: "{{ lmdb_path }}"
    mode: u=rwx,g=rwx,o=rwx
    recurse: yes
    state: directory

- name: Update LMDB Dates
  become_user: "{{ deploy_user }}"
  script: lmdb_check.py
  environment:
    POSTGRES_HOST: "{{ POSTGRES_HOST }}"
    POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"
    POSTGRES_PORT: "{{ POSTGRES_PORT }}"
    POSTGRES_USER: "{{ POSTGRES_USER }}"
    POSTGRES_DB: "{{ POSTGRES_DB }}"
  register: outcome

- debug: msg="{{ outcome.stdout }}"
