apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "***ARANGO_DB_NAME***.fullname" . }}-pdfparser
  labels:
    app.kubernetes.io/component: pdfparser
    {{- include "***ARANGO_DB_NAME***.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "***ARANGO_DB_NAME***.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: pdfparser
  replicas: {{ .Values.pdfparser.replicaCount }}
  strategy:
    type: {{ .Values.pdfparser.strategyType | default "RollingUpdate" }}
  template:
    metadata:
      annotations: {{ toYaml (default dict .Values.pdfparser.podAnnotations) | nindent 8 }}
      labels:
        {{- include "***ARANGO_DB_NAME***.selectorLabels" . | nindent 8 }}
        {{- if .Values.pdfparser.podLabels }}
        {{ toYaml .Values.pdfparser.podLabels | indent 8 }}
        {{- end }}
        app.kubernetes.io/component: pdfparser
    spec:
      {{- include "***ARANGO_DB_NAME***.podSpec" .Values.pdfparser | nindent 6 }}
      containers:
      - name: {{ .Chart.Name }}-pdfparser
        {{- include "***ARANGO_DB_NAME***.image" (dict "image" .Values.pdfparser.image "Chart" .Chart) | nindent 8 }}
        {{- include "***ARANGO_DB_NAME***.healthChecks" .Values.pdfparser | nindent 8 }}
        resources: {{ toYaml (default dict .Values.pdfparser.resources) | nindent 10 }}
        ports:
        - containerPort: {{ .Values.pdfparser.service.port }}
        tty: true
        env:
        {{- range $envName, $envValue := (default dict .Values.pdfparser.extraEnv) }}
        - name: {{ $envName }}
          value: {{ $envValue | quote }}
        {{- end }}
