#!/bin/sh

# Path from shell to folder containing this file
__dir__="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

# Runs linting on only files that are staged
staged_files=$(getStaged statistical-enrichment '\.(py)$')

if [[ -n $staged_files ]]; then
    (
        echo "> 🌽 Running flake8..."
        echo ${staged_files} | xargs \
            docker run --rm \
            -v $(pwd)/appserver:/apps \
            alpine/flake8:6.0.0
    ) && (
        echo "> 🐍 Running pycodestyle..."
        echo ${staged_files} | xargs \
            docker run --rm \
            -v $(pwd)/appserver:/data \
            cytopia/pycodestyle:2
    )
else
    echo "> Skipping python files check for statistical-enrichment..."
fi
