#!/bin/sh

# Path from shell to folder containing this file
__dir__="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# Runs linting on only files that are staged
staged_files=$(getStaged appserver '\.(py)$')

# Turn debugging on by the flag
if [[ -n $DEBUG_HOOKS ]];
then
  echo "> 🐛 flake8 version:"
  docker run --rm alpine/flake8:6.0.0 --version
  echo "> 🐛 mypy version:"
  $DOCKER_COMPOSE_RUN --no-deps appserver mypy --version
  echo "> 🐛 pycodestyle version:"
  docker run --rm cytopia/pycodestyle:2 --version
fi

# shellcheck disable=SC2236
if [[ -n $staged_files ]];
then
   (
    echo "> 🌽 Running flake8..."
    echo ${staged_files} | \
      xargs docker run --rm \
      -v $(pwd)/appserver:/apps \
      alpine/flake8:6.0.0
  ) && (
    echo "> 🥧 Running mypy..."
    echo ${staged_files} | xargs $DOCKER_COMPOSE_RUN --no-deps appserver mypy
  ) && (
    echo "> 🐍 Running pycodestyle..."
    echo ${staged_files} | \
      xargs docker run --rm \
      -v $(pwd)/appserver:/data \
      cytopia/pycodestyle:2
  )
else
  echo "> Skipping python files check for appserver..."
fi
