name: Client Lint Autofix
description: Runs TsLint autofix on the client directory and pushes the changes to the repository

inputs:
  git_name:
    description: Username for auto-fix commits
    required: false
    default: Lint Action
  git_email:
    description: Email address for auto-fix commits
    required: false
    default: "lint-action@samuelmeuli.com"
  commit_message:
    description: Auto-fix commit message
    required: false
    default: "Fix code style issues with TsLint"

runs:
  using: composite
  steps:
    - name: Setup Node.js
      if: github.event.inputs.autoFix && github.event.inputs.tslintAutoFix
      uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: yarn
        cache-dependency-path: client/yarn.lock

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Run linter
      run: yarn lint-ci --fix

    - name: Commit and push changes
      run: |
        git config --global user.name "{{ github.event.inputs.git_name }}"
        git config --global user.email "{{ github.event.inputs.git_email }}"
        git commit -am "${{ github.event.inputs.commit_message }}"
        git push


