name: Annotate code style

on:
  pull_request:
  workflow_dispatch:
    inputs:
      autoFix:
        description: "Auto Fix"
        required: false
        default: false
        type: boolean
      blackAutoFix:
        description: "Black Auto Fix"
        required: false
        default: true
        type: boolean
      prettierAutoFix:
        description: "Prettier Auto Fix"
        required: false
        default: true
        type: boolean
  issue_comment:
    types: [created]


jobs:
  appserver:
    name: Annotate code style
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Annotate code style
        uses: wearerequired/lint-action@v2
        with:
          auto_fix: ${{
            github.event.inputs.autoFix ||
            (github.event.comment == 'autofix' && github.event.sender == github.event.pull_request.user)
          }}
          neutral_check_on_warning: true
          continue_on_error: true
          black: true
          black_auto_fix: ${{ github.event.inputs.blackAutoFix || true }}
          black_command_prefix: |-
            docker run --rm -v $(pwd):/work --workdir /work pyfound/black:latest_release
          prettier: true
          prettier_auto_fix: ${{ github.event.inputs.prettierAutoFix || true }}
          prettier_command_prefix: |-
            docker run --rm -v $(pwd):/work tmknom/prettier
