name: Annotate code style

on:
  pull_request_target:
    types: [labeled, synchronize]

jobs:
  appserver:
    name: Annotate code style
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Annotate code style
        uses: wearerequired/lint-action@v2
        with:
          neutral_check_on_warning: true
          continue_on_error: true
          black: {{
            github.event.label.name == 'backend' ||
            contains(github.event.pull_request.labels.*.name, 'backend')
          }}
          black_command_prefix: |-
            docker run --rm -v $(pwd):/work --workdir /work pyfound/black:latest_release
          prettier: {{
            github.event.label.name == 'frontend' ||
            contains(github.event.pull_request.labels.*.name, 'frontend')
          }}
          prettier_command_prefix: |-
            docker run --rm -v $(pwd):/work tmknom/prettier
