name: Appserver Pytest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Appserver and Run Pytests
      run: |
        docker-compose -f docker-compose.pytest-workflow.yml up --build -d
        ./appserver/bin/wait-for-flask
        docker-compose exec -T appserver pytest tests
