name: Azure Deployment

on:
  push:
    tags:
      - "azure"

jobs:
  build:
    name: Setup, Build, Publish
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.timestamp.outputs.commit_timestamp }}
      output2: ${{ steps.commitcount.outputs.build_number }}
      output3: ${{ steps.buildversion.outputs.build_version}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set git commit timestamp
        id: timestamp
        run: echo ::set-output name=commit_timestamp::$(git log -1 --format=%cI)

      - name: Set commit counts as build number
        id: commitcount
        run: echo ::set-output name=build_number::$(git rev-list --count HEAD)

        # Uses the commit tag as the version
      - name: Set build version
        id: buildversion
        run: echo ::set-output name=build_version::$(echo "${GITHUB_REF#refs/*/}")

      - name: Build appserver image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.AZURE_CR_USERNAME }}
          password: ${{ secrets.AZURE_CR_PASSWORD }}
          registry: lifelike.azurecr.io
          image_name: kg-appserver
          image_tag: ${{ github.sha }},latest
          context: ./appserver
          dockerfile: ./Dockerfile

      - name: Build Client and Nginx Image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.AZURE_CR_USERNAME }}
          password: ${{ secrets.AZURE_CR_PASSWORD }}
          registry: lifelike.azurecr.io
          image_name: kg-webserver
          image_tag: ${{ github.sha }},latest
          context: ./client
          dockerfile: ./Dockerfile

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SERVICE_CREDENTIALS }}

      - name: Deploy Appserver
        uses: azure/webapps-deploy@v2
        with:
          app-name: lifelike-app
          configuration-file: docker-compose.azure.yml

