name: Trigger Target Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Webhook
        run: |
          # Set the required variables
          repo_owner="biosustain"
          repo_name="lifelike-infrastructure"
          load=$(
            cat<<'---'
            {
              "event_type": "Source code update",
              "client_payload": {
                "caller": "${{ github.workflow }}",
                "repository": "${{ github.repository }}",
                "run_id": "${{ github.run_id }}"
              }
            }
            ---
          )

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.WEBHOOK_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "$load"
