name: Build and push frontend client Docker image

on:
  push:
    branches:
      - 'master'
    paths:
      - 'client/**'
      - '.github/**'

jobs:
  doker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker publish
        uses: ./.github/actions/docker-publish.yml
        with:
          image: ***ARANGO_DB_NAME***/client
          dockerfile: ./client/Dockerfile
          context: ./client
