name: Build and push client Docker image

on:
  push:
    branches:
      - 'master'
    paths:
      - 'client/**'
      - '.github/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Write git info to Docker image
        run: |
          cd api
          echo ${{ env.GITHUB_REF_SLUG }} > CI_COMMIT_REF_NAME
          echo ${GITHUB_SHA} > CI_COMMIT_SHA
          echo ${{ steps.meta-build.outputs.tags }} > IMAGE_TAG

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            client
          flavor: |
            latest=${{ startsWith(github.ref, 'refs/heads/main') }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: ***ARANGO_DB_NAME***.azurecr.io
          username: ${{ secrets.AZURE_CR_USERNAME }}
          password: ${{ secrets.AZURE_CR_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: client/Dockerfile
          context: client/
          push: true
          tags: ${{ steps.meta .outputs.tags }}
