name: GCP Demo Deployment

on:
  workflow_dispatch:
  push:
    tags: [demo]

jobs:
  call-deployment-gcp:
    uses: ./.github/workflows/deployment-gcp.yml
    with:
      environment_name: demo
      client_config: demo
    secrets:
      CONTAINER_REGISTRY_USERNAME: ${{ secrets.AZURE_CR_USERNAME }}
      CONTAINER_REGISTRY_PASSWORD: ${{ secrets.AZURE_CR_PASSWORD }}
