name: Contabo UCSD Deployment

on:
  workflow_dispatch:
  push:
    tags: [ucsd]
    branches: [ucsd/**]

jobs:
  call-deployment-contabo:
    uses: ./.github/workflows/deployment-contabo.yml
    with:
      environment_name: ucsd
      client_config: staging
    secrets:
      VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT }}
      SSH_KEY: ${{ secrets.ANSIBLE_PRIVATE_SSH_KEY }}
      CONTAINER_REGISTRY_USERNAME: ${{ secrets.AZURE_CR_USERNAME }}
      CONTAINER_REGISTRY_PASSWORD: ${{ secrets.AZURE_CR_PASSWORD }}
      INFRA_PAT: ${{ secrets.INFRA_PAT }}
