name: Pull Request Handler
on: [pull_request_target]

jobs:
  label:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true

  backend_code_style:
    needs: label
    if: ${{ contains(github.event.pull_request.labels.*.name, 'backend') }}
    name: Annotate backend code style
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Annotate code style
        uses: wearerequired/lint-action@v2
        with:
          neutral_check_on_warning: true
          continue_on_error: true
          black: true
          black_command_prefix: docker run --rm -v $(pwd):/work --workdir /work pyfound/black:latest_release

  frontend_code_style:
    needs: label
    if: ${{ contains(github.event.pull_request.labels.*.name, 'frontend') }}
    name: Annotate fontend code style
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Annotate code style
        uses: wearerequired/lint-action@v2
        with:
          neutral_check_on_warning: true
          continue_on_error: true
          prettier: true
          prettier_command_prefix: docker run --rm -v $(pwd):/work tmknom/prettier
