name: PR review labels

on:
  pull_request:
    types:
      - labeled
      - ready_for_review
  pull_request_review:
    types:
      - edited
      - dismissed
      - submitted

jobs:
  review-labels:
    runs-on: ubuntu-latest
    steps:
      - id: reviews
        uses: jrylan/github-action-reviews-counter@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - run: echo "::group::PR review labels"

      - name: changes requested
        uses: buildsville/add-remove-label@v1
        with:
          label: changes requested
          type: "${{ steps.reviews.outputs.changes_requested > 0 ? 'add' : 'remove' }}"
          token: ${{secrets.GITHUB_TOKEN}}

      - name: waiting for review
        uses: buildsville/add-remove-label@v1
        with:
          label: waiting for review
          type: "${{ steps.reviews.outputs.pending > 0 ? 'add' : 'remove' }}"
          token: ${{secrets.GITHUB_TOKEN}}

      - name: approved
        uses: buildsville/add-remove-label@v1
        with:
          label: approved
          type: "${{ steps.reviews.outputs.approved >= 1 && steps.reviews.outputs.changes_requested == 0 && 'add' || 'remove' }}"
          token: ${{secrets.GITHUB_TOKEN}}

      - run: echo "::endgroup::"
