name: Staging Deployment

on:
    pull_request:
        types: [labeled]

env:
    SERVICE_ACCOUNT_CRED: ${{ secrets.GCE_SA_KEY }}
    POSTGRES_HOST: ${{ secrets.STAGING_POSTGRES_HOST }}
    POSTGRES_PORT: ${{ secrets.STAGING_POSTGRES_PORT }}
    POSTGRES_USER: ${{ secrets.STAGING_POSTGRES_USER }}
    POSTGRES_PASSWORD: ${{ secrets.STAGING_POSTGRES_PASSWORD }}
    POSTGRES_DB: ${{ secrets.STAGING_POSTGRES_DB }}
    NEO4J_HOST: ${{ secrets.STAGING_NEO4J_HOST }}
    NEO4J_AUTH: ${{ secrets.STAGING_NEO4J_AUTH }}
    FLASK_APP: ${{ secrets.STAGING_FLASK_APP }}
    FLASK_APP_CONFIG: ${{ secrets.STAGING_FLASK_APP_CONFIG }}
    FLASK_ENV: ${{ secrets.STAGING_FLASK_ENV }}
    PROJECT_ID: ${{ secrets.GCE_PROJECT }}
    GCE_INSTANCE: kg-staging
    GCE_INSTANCE_ZONE: us-central1-a

jobs:
    setup-build-publish-deploy:

        name: Setup, Build, Publish, and Deploy
        runs-on: ubuntu-latest

        if: contains(github.event.pull_request.labels.*.name, 'staging')

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            # Setup gcloud CLI
            # https://github.com/GoogleCloudPlatform/github-actions
            - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
              with:
                version: '286.0.0'
                service_account_key: ${{ secrets.GCE_SA_KEY }}
                project_id: ${{ secrets.GCE_PROJECT }}

            # Configure Docker to use gcloud command line tool
            - run: |-
                gcloud --quiet auth configure-docker

            # Build the Docker images
            - name: Build
              run: |-
                docker build --tag "gcr.io/$PROJECT_ID/kg-appserver-staging:latest" -f ./appserver/Dockerfile.prod ./appserver/
                docker build --tag "gcr.io/$PROJECT_ID/kg-webserver-staging:latest" -f ./client/Dockerfile.staging ./client/

            # # Push Docker image to Google Container Registry
            - name: Publish
              run: |-
                docker push "gcr.io/$PROJECT_ID/kg-appserver-staging:latest"
                docker push "gcr.io/$PROJECT_ID/kg-webserver-staging:latest"

            - name: Deploy Setup
              run: |-
                echo "POSTGRES_HOST=$POSTGRES_HOST" >> staging.env
                echo "POSTGRES_PORT=$POSTGRES_PORT" >> staging.env
                echo "POSTGRES_USER=$POSTGRES_USER" >> staging.env
                echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> staging.env
                echo "POSTGRES_DB=$POSTGRES_DB" >> staging.env
                echo "NEO4J_HOST=$NEO4J_HOST" >> staging.env
                echo "NEO4J_AUTH=$NEO4J_AUTH" >> staging.env
                echo "FLASK_APP=$FLASK_APP" >> staging.env
                echo "FLASK_APP_CONFIG=$FLASK_APP_CONFIG" >> staging.env
                echo "FLASK_ENV=$FLASK_ENV" >> staging.env
                echo "DOCKER_USER=_json_key" >> staging.env
                echo "PROJECT_ID=$PROJECT_ID" >> staging.env
                echo "$SERVICE_ACCOUNT_CRED" >> keyfile.json
                gcloud compute scp staging.env ***ARANGO_USERNAME***@$GCE_INSTANCE:/srv --zone $GCE_INSTANCE_ZONE
                gcloud compute scp keyfile.json ***ARANGO_USERNAME***@$GCE_INSTANCE:/srv --zone $GCE_INSTANCE_ZONE
                gcloud compute scp ./deployment/bin/startup.sh ***ARANGO_USERNAME***@$GCE_INSTANCE:/srv --zone $GCE_INSTANCE_ZONE
                gcloud compute ssh ***ARANGO_USERNAME***@$GCE_INSTANCE --zone $GCE_INSTANCE_ZONE --command='chmod a+x /srv/startup.sh';

            - name: Deploy
              run: |-
                gcloud compute ssh ***ARANGO_USERNAME***@$GCE_INSTANCE --zone $GCE_INSTANCE_ZONE --command='/srv/startup.sh';
                gcloud compute ssh ***ARANGO_USERNAME***@$GCE_INSTANCE --zone $GCE_INSTANCE_ZONE --command='sudo docker system prune';