name: Staging Deployment

on:
  push:
    branches:
      - master

env:
    POSTGRES_HOST: ${{ secrets.STAGING_POSTGRES_HOST }}
    POSTGRES_PORT: ${{ secrets.STAGING_POSTGRES_PORT }}
    POSTGRES_USER: ${{ secrets.STAGING_POSTGRES_USER }}
    POSTGRES_PASSWORD: ${{ secrets.STAGING_POSTGRES_PASSWORD }}
    POSTGRES_DB: ${{ secrets.STAGING_POSTGRES_DB }}
    NEO4J_HOST: ${{ secrets.STAGING_NEO4J_HOST }}
    NEO4J_AUTH: ${{ secrets.STAGING_NEO4J_AUTH }}
    FLASK_APP: ${{ secrets.STAGING_FLASK_APP }}
    FLASK_APP_CONFIG: ${{ secrets.STAGING_FLASK_APP_CONFIG }}
    FLASK_ENV: ${{ secrets.STAGING_FLASK_ENV }}
    PROJECT_ID: ${{ secrets.GCE_PROJECT }}
    GITHUB_HASH: $GITHUB_SHA
    GCE_INSTANCE: kg-staging
    GCE_INSTANCE_ZONE: us-central1-a
    GCE_SERVICE_ACCOUNT: ${{ secrets.GCE_SA_KEY }}
    CLOUD_SQL_ALIAS: ${{ secrets.STAGING_CLOUD_SQL_ALIAS }}
    GCE_BACKUP_BUCKET: ${{ secrets.POSTGRES_BACKUP_BUCKET }}
    SENTRY_KEY: ${{ secrets.SENTRY_KEY }}

jobs:

    setup-build-publish-deploy:

        name: Setup, Build, Publish, and Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            # Setup gcloud CLI
            # https://github.com/GoogleCloudPlatform/github-actions
            - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
              with:
                version: '286.0.0'
                service_account_key: ${{ secrets.GCE_SA_KEY }}
                project_id: ${{ secrets.GCE_PROJECT }}

            # Configure Docker to use gcloud command line tool
            - run: |-
                gcloud --quiet auth configure-docker

            # Build the Docker images
            - name: Build
              run: |-
                docker build --tag "gcr.io/$PROJECT_ID/kg-appserver-staging:latest" -f ./appserver/Dockerfile.prod ./appserver/
                docker build --tag "gcr.io/$PROJECT_ID/kg-webserver-staging:latest" -f ./client/Dockerfile.staging ./client/

            # # Push Docker image to Google Container Registry
            - name: Publish
              run: |-
                docker push "gcr.io/$PROJECT_ID/kg-appserver-staging:latest"
                docker push "gcr.io/$PROJECT_ID/kg-webserver-staging:latest"

            - name: Deploy Setup
              run: |-
                echo "POSTGRES_HOST=$POSTGRES_HOST" >> staging.env
                echo "POSTGRES_PORT=$POSTGRES_PORT" >> staging.env
                echo "POSTGRES_USER=$POSTGRES_USER" >> staging.env
                echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> staging.env
                echo "POSTGRES_DB=$POSTGRES_DB" >> staging.env
                echo "NEO4J_HOST=$NEO4J_HOST" >> staging.env
                echo "NEO4J_AUTH=$NEO4J_AUTH" >> staging.env
                echo "FLASK_APP=$FLASK_APP" >> staging.env
                echo "FLASK_APP_CONFIG=$FLASK_APP_CONFIG" >> staging.env
                echo "FLASK_ENV=$FLASK_ENV" >> staging.env
                echo "DOCKER_USER=_json_key" >> staging.env
                echo "PROJECT_ID=$PROJECT_ID" >> staging.env
                echo "CLOUD_SQL_ALIAS=$CLOUD_SQL_ALIAS" >> staging.env
                echo "GCE_BACKUP_BUCKET=$GCE_BACKUP_BUCKET" >> staging.env
                echo "SERVICE_ACCOUNT_CRED=$GCE_SERVICE_ACCOUNT" >> staging.env
                GITHUB_COMMIT_TIMESTAMP=$(git log -1 --format=%cI)
                echo "GITHUB_COMMIT_TIMESTAMP=$GITHUB_COMMIT_TIMESTAMP" >> staging.env
                echo "GITHUB_HASH=$GITHUB_HASH" >> staging.env
                echo "SENTRY_KEY=$SENTRY_KEY" >> staging.env
                echo "$GCE_SERVICE_ACCOUNT" >> keyfile.json
                gcloud compute scp staging.env root@$GCE_INSTANCE:/srv --zone $GCE_INSTANCE_ZONE
                gcloud compute scp keyfile.json root@$GCE_INSTANCE:/srv --zone $GCE_INSTANCE_ZONE
                gcloud compute scp ./deployment/bin/startup.sh root@$GCE_INSTANCE:/srv --zone $GCE_INSTANCE_ZONE
                gcloud compute scp ./deployment/bin/migration-manager.sh root@$GCE_INSTANCE:/srv --zone $GCE_INSTANCE_ZONE
                gcloud compute ssh root@$GCE_INSTANCE --zone $GCE_INSTANCE_ZONE --command='chmod a+x /srv/startup.sh';
                gcloud compute ssh root@$GCE_INSTANCE --zone $GCE_INSTANCE_ZONE --command='chmod a+x /srv/migration-manager.sh';

            - name: Save encrypted copy of environment file to Google Bucket
              run: |-
                gcloud kms encrypt --location global --keyring kg-secrets --key kg-secrets-key --plaintext-file staging.env --ciphertext-file staging.env.encrypted
                gsutil cp staging.env.encrypted gs://kg-secrets/staging.env.encrypted

            - name: Deploy
              run: |-
                gcloud compute ssh root@$GCE_INSTANCE --zone $GCE_INSTANCE_ZONE --command='/srv/startup.sh -t staging';

            - name: Applying database migrations
              run: |-
                gcloud compute ssh root@$GCE_INSTANCE --zone $GCE_INSTANCE_ZONE --command='/srv/migration-manager.sh -t staging';

            - name: Clean up images
              run: |-
                gcloud compute ssh root@$GCE_INSTANCE --zone $GCE_INSTANCE_ZONE --command='sudo docker system prune -f';
