name: Azure Traefik deployment

on:
  workflow_dispatch:
  push:
    tags: [traefik-az]
    branches: [traefik-az/**]

jobs:
  call-deployment-gcp:
    uses: ./.github/workflows/traefik.yml
    with:
      playbook_path: playbooks/proxy-azure.yml
      inventory_path: inventories/hosts-az.yml
    secrets:
      VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT }}
      SSH_KEY: ${{ secrets.ANSIBLE_PRIVATE_SSH_KEY }}
      INFRA_PAT: ${{ secrets.INFRA_PAT }}
