#!/bin/sh

# Runs linting on only files that are staged
staged_files=$(getStaged post-annotator '\.(py)$')

# Turn debugging on by the flag
if [[ -n $DEBUG_HOOKS ]];
then
  echo "> 🐛 flake8 version:"
  docker exec post-annotator flake8 --version
  echo "> 🐛 mypy version:"
  docker exec post-annotator mypy --version
  echo "> 🐛 pycodestyle version:"
  docker exec post-annotator pycodestyle --version
fi

# shellcheck disable=SC2236
if [[ -n $staged_files ]];
then
  (
    echo "> 🌽 Running flake8..."
    echo ${staged_files} | xargs docker exec post-annotator flake8
  ) && (
    echo "> 🥧 Running mypy..."
    echo ${staged_files} | xargs docker exec post-annotator mypy
  ) && (
    echo "> 🐍 Running pycodestyle..."
    echo ${staged_files} | xargs docker exec post-annotator pycodestyle
  )
else
  echo "> Skipping..."
fi
