http:
  routers:
    dashboard:
      rule: "Host(`traefik.***ARANGO_DB_NAME***.bio`)"
      service: api@internal
      middlewares:
        - admin-auth
      tls:
        certResolver: "le"
        domains:
          - main: "traefik.***ARANGO_DB_NAME***.bio"
    ***ARANGO_DB_NAME***-qa:
      entryPoints:
        - websecure
      rule: "Host(`qa.***ARANGO_DB_NAME***.bio`)"
      service: ***ARANGO_DB_NAME***-qa-service
      tls:
        certResolver: "le"
        domains:
          - main: "qa.***ARANGO_DB_NAME***.bio"
    ***ARANGO_DB_NAME***-staging:
      entryPoints:
        - websecure
      rule: "Host(`staging.***ARANGO_DB_NAME***.bio`)"
      service: ***ARANGO_DB_NAME***-staging-service
      tls:
        certResolver: "le"
        domains:
          - main: "staging.***ARANGO_DB_NAME***.bio"
    ***ARANGO_DB_NAME***-prod:
      entryPoints:
        - websecure
      rule: "Host(`***ARANGO_DB_NAME***.bio`)"
      service: ***ARANGO_DB_NAME***-prod-service
      tls:
        certResolver: "le"
        domains:
          - main: "***ARANGO_DB_NAME***.bio"
    ***ARANGO_DB_NAME***-elk-qa:
      entryPoints:
        - websecure
      rule: "Host(`elk.***ARANGO_DB_NAME***.bio`)"
      service: ***ARANGO_DB_NAME***-elk-qa
      tls:
        certResolver: "le"
        domains:
          - main: "elk.***ARANGO_DB_NAME***.bio"

  services:
    ***ARANGO_DB_NAME***-qa-service:
      loadBalancer:
        servers:
          - url: "http://10.128.15.243"
    ***ARANGO_DB_NAME***-staging-service:
      loadBalancer:
        servers:
          - url: "http://10.128.15.207"
    ***ARANGO_DB_NAME***-prod-service:
      loadBalancer:
        servers:
          - url: "http://10.128.15.235"
    ***ARANGO_DB_NAME***-elk-qa:
      loadBalancer:
        servers:
          - url: "http://10.128.15.244"

  middlewares:
    admin-auth:
      basicAuth:
        users:
          - "{{ traefik_credentials }}"
