http:
  routers:
    dashboard:
      rule: "Host(`azure.***ARANGO_DB_NAME***.bio`)"
      service: api@internal
      middlewares:
        - admin-auth
      tls:
        certResolver: "le"
        domains:
          - main: "azure.***ARANGO_DB_NAME***.bio"
    ***ARANGO_DB_NAME***-qa:
      entryPoints:
        - websecure
      rule: "Host(`azureqa.***ARANGO_DB_NAME***.bio`)"
      service: ***ARANGO_DB_NAME***-qa-service
      tls:
        certResolver: "le"
        domains:
          - main: "azureqa.***ARANGO_DB_NAME***.bio"

  services:
    ***ARANGO_DB_NAME***-qa-service:
      loadBalancer:
        servers:
          - url: "http://10.0.100.5"

  middlewares:
    admin-auth:
      basicAuth:
        users:
          - "{{ traefik_credentials }}"
