http:
  routers:
    dashboard:
      rule: "Host(`azure.lifelike.bio`)"
      service: api@internal
      middlewares:
        - admin-auth
      tls:
        certResolver: "le"
        domains:
          - main: "azure.lifelike.bio"
    lifelike-qa:
      entryPoints:
        - websecure
      rule: "Host(`azureqa.lifelike.bio`)"
      service: lifelike-qa-service
      tls:
        certResolver: "le"
        domains:
          - main: "azureqa.lifelike.bio"

  services:
    lifelike-qa-service:
      loadBalancer:
        servers:
          - url: "http://10.0.100.5"

  middlewares:
    admin-auth:
      basicAuth:
        users:
          - "{{ traefik_credentials }}"
