log:
  level: "{{ traefik_log_level }}"

providers:
  file:
    filename: "{{ traefik_service_yml }}"
    watch: true

api:
  insecure: false
  dashboard: true

certificatesResolvers:
  le:
    acme:
      email: "{{ traefik_lets_encrypt_email }}"
      storage: acme.json
      tlsChallenge: {}

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
